import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MartinHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/">
          <h1 className="mt-4 text-center text-2xl font-bold">
            Martin<span className="rounded bg-yellow-500 p-1">Hub</span>
          </h1>
        </Link>
        {children}
      </body>
    </html>
  );
}
